openapi: 3.0.0
info:
  version: 1.0.0
  title: System Vulnerability Scan API
servers:
  - url: 'http://atom-scout-api-server/v0/svs/'
paths:
  /patterns/version:
    get:
      summary: List SVS pattern version.
      operationId: listPatternVersion
      tags:
        - patterns
      responses:
        '200':
          description: Provide pattern version
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      version: 
                        type: string
                        example: "FA2526A60920E95BF19858B381CDD4A356A6559F"
                  message:
                    type: string
                    example: success
        400:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /patterns:
    get:
      summary: List all sacnning patterns.
      operationId: listPatterns
      tags:
        - patterns
      parameters:
        - $ref: "#/components/parameters/Auth_DN"
        - $ref: "#/components/parameters/Auth_VERIFIED"
      responses:
        '200':
          description: Array of patterns
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      static:
                        type: array
                        items:
                          type: object
                          properties:
                            target:
                              type: string
                              example: libssl
                            type:
                              type: string
                              example: 1
                            pettern:
                              type: string
                              example: '^OpenSSL ([0-9]+\.[0-9]+\.[0-9]+[a-z]*)'
                            section:
                              type: string
                              example: .rodata
                      dynamic:
                        type: array
                        items:
                          type: object
                          properties:
                            functions:
                              type: array
                              items:
                                type: object
                                properties:
                                  argument:
                                    type: integer
                                    example: 0
                                  prototype:
                                    type: integer
                                    example: 1
                                  symbol:
                                    type: string
                            target:
                              type: string
                  message:
                    type: string
                    example: success
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /devices/touch:
    put:
      summary: Touch to update device's basic information.
      operationId: touchDeviceInfo
      tags:
        - devices
      parameters:
        - $ref: "#/components/parameters/Auth_DN"
        - $ref: "#/components/parameters/Auth_VERIFIED"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                model_name:
                  type: string
                  example: Model A
                library_hash:
                  type: string
                  example: >-
                    ca48b6dedc534310688645f42beadb99cb457538c21f49f269ebb75e406a498f
                collect_detail:
                  type: boolean
                  example: f
                platform:
                  type: string
                  example: 'Raspberry Pi 3'
      responses:
        '200':
          description: Update successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      baseline_diff:
                        type: boolean
                        example: t
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /devices/info:
    put:
      summary: Update device's detail system information.
      operationId: updateDeviceDetail
      tags:
        - devices
      parameters:
        - $ref: "#/components/parameters/Auth_DN"
        - $ref: "#/components/parameters/Auth_VERIFIED"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cpu:
                  type: object
                  additionalProperties:
                    type: string
                memory:
                  type: object
                  additionalProperties:
                    type: string
                os:
                  type: object
                  additionalProperties:
                    type: string
                kernel:
                  type: object
                  properties:
                    version:
                      type: string
      responses:
        '200':
          description: Update successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                  message:
                    type: string
                    example: success
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /devices/baseline:
    put:
      summary: Update device's baseline information.
      operationId: updateDeviceBaseline
      tags:
        - devices
      parameters:
        - $ref: "#/components/parameters/Auth_DN"
        - $ref: "#/components/parameters/Auth_VERIFIED"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                library_hash:
                  type: string
                known:
                  type: array
                  items:
                    type: object
                    properties:
                      libname:
                        type: string
                      version:
                        type: string
                      path:
                        type: string
                suspect:
                  type: array
                  items:
                    type: object
                    properties:
                      libname:
                        type: string
                      version:
                        type: string
                      path:
                        type: string
                unknown:
                  type: array
                  items:
                    type: object
                    properties:
                      libname:
                        type: string
                      version:
                        type: string
                      path:
                        type: string
      responses:
        '200':
          description: Update successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                  message:
                    type: string
                    example: success
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  parameters:
    Auth_DN:
      name: DN
      in: header
      description: uwsgi_parm "DN" is a string contains vender_key_id and device_id.
      required: true
      schema:
        type: string
    Auth_VERIFIED:
      name: VERIFIED
      in: header
      description: uwsgi_parm "VERIFIED" is used to check if request passed the authentication. 
      required: true
      schema:
        type: string
        example: "SUCCESS"
  schemas:
    Error:
      required:
        - error_code
      properties:
        error_code:
          type: integer
          example: 10001